[build]
  command = "ng build --configuration production" # lệnh để build Angular project
  publish = "dist/unicourse-client/browser" # đường dẫn thư mục xuất bản mà Netlify sẽ sử dụng

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200